# Generated by Django 4.0.6 on 2022-08-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_address_dish_restaurant_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
